# Generated by Django 2.1 on 2019-02-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appartments',
            options={'verbose_name_plural': 'Appartments'},
        ),
    ]
