# Generated by Django 2.1 on 2019-02-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_auto_20190224_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartments',
            name='slug',
            field=models.SlugField(default='title', max_length=100),
        ),
    ]
