# Generated by Django 2.1 on 2019-02-24 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_appartments_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appartments',
            name='slug',
        ),
    ]
