# Generated by Django 2.1 on 2019-02-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_remove_appartments_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartments',
            name='slug',
            field=models.SlugField(default='irabi', max_length=200),
        ),
    ]
