# Generated by Django 2.1 on 2019-03-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_appartments_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartments',
            name='Bathroom',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='appartments',
            name='Bedrooms',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='appartments',
            name='area_range',
            field=models.PositiveIntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='appartments',
            name='image',
            field=models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='appartments',
            name='kitchen',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=10),
        ),
    ]
