# Generated by Django 2.1 on 2019-03-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0007_appartments_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=100)),
                ('phone_number', models.PositiveIntegerField()),
                ('check_in', models.CharField(max_length=25)),
                ('check_out', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Booking Details',
            },
        ),
    ]
